name: budget-on-push
on: [push]
jobs:
  run-prettier:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: npx prettier . --write
  run-vitest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: npm install
    - run: vitest run
